/*
 * Decompiled with CFR 0.152.
 */
package com.seedfinding.mcbiome.biome;

import com.seedfinding.mcbiome.biome.Biome;
import com.seedfinding.mcbiome.biome.surface.ConfiguredSurfaceBuilders;
import com.seedfinding.mccore.state.Dimension;
import com.seedfinding.mccore.version.MCVersion;
import java.util.HashMap;
import java.util.Map;

public class Biomes {
    public static final Map<Integer, Biome> REGISTRY = new HashMap<Integer, Biome>();
    public static final Biome OCEAN = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.OVERWORLD, 0, "ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.0f, null, ConfiguredSurfaceBuilders.GRASS));
    public static final Biome PLAINS = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.OVERWORLD, 1, "plains", Biome.Category.PLAINS, Biome.Precipitation.RAIN, 0.8f, 0.05f, 0.125f, null, ConfiguredSurfaceBuilders.GRASS));
    public static final Biome DESERT = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.OVERWORLD, 2, "desert", Biome.Category.DESERT, Biome.Precipitation.NONE, 2.0f, 0.05f, 0.125f, null, ConfiguredSurfaceBuilders.DESERT));
    public static final Biome MOUNTAINS;
    public static final Biome EXTREME_HILLS;
    public static final Biome FOREST;
    public static final Biome TAIGA;
    public static final Biome SWAMP;
    public static final Biome SWAMPLAND;
    public static final Biome RIVER;
    public static final Biome NETHER_WASTES;
    public static final Biome HELL;
    public static final Biome THE_END;
    public static final Biome SKY;
    public static final Biome FROZEN_OCEAN;
    public static final Biome FROZEN_RIVER;
    public static final Biome SNOWY_TUNDRA;
    public static final Biome ICE_PLAINS;
    public static final Biome ICE_FLATS;
    public static final Biome SNOWY_MOUNTAINS;
    public static final Biome ICE_MOUNTAINS;
    public static final Biome MUSHROOM_FIELDS;
    public static final Biome MUSHROOM_ISLAND;
    public static final Biome MUSHROOM_FIELD_SHORE;
    public static final Biome MUSHROOM_ISLAND_SHORE;
    public static final Biome BEACH;
    public static final Biome BEACHEs;
    public static final Biome DESERT_HILLS;
    public static final Biome WOODED_HILLS;
    public static final Biome FOREST_HILLS;
    public static final Biome TAIGA_HILLS;
    public static final Biome MOUNTAIN_EDGE;
    public static final Biome EXTREME_HILLS_EDGE;
    public static final Biome SMALLER_EXTREME_HILLS;
    public static final Biome JUNGLE;
    public static final Biome JUNGLE_HILLS;
    public static final Biome JUNGLE_EDGE;
    public static final Biome DEEP_OCEAN;
    public static final Biome STONE_SHORE;
    public static final Biome STONE_BEACH;
    public static final Biome SNOWY_BEACH;
    public static final Biome COLD_BEACH;
    public static final Biome BIRCH_FOREST;
    public static final Biome BIRCH_FOREST_HILLS;
    public static final Biome DARK_FOREST;
    public static final Biome ROOFED_FOREST;
    public static final Biome SNOWY_TAIGA;
    public static final Biome COLD_TAIGA;
    public static final Biome SNOWY_TAIGA_HILLS;
    public static final Biome COLD_TAIGA_HILLs;
    public static final Biome GIANT_TREE_TAIGA;
    public static final Biome MEGA_TAIGA;
    public static final Biome REDWOOD_TAIGA;
    public static final Biome GIANT_TREE_TAIGA_HILLS;
    public static final Biome MEGA_TAIGA_HILLs;
    public static final Biome REDWOOD_TAIGA_HILLs;
    public static final Biome WOODED_MOUNTAINS;
    public static final Biome EXTREME_HILLS_PLUS;
    public static final Biome EXTREME_HILLS_WITH_TREES;
    public static final Biome SAVANNA;
    public static final Biome SAVANNA_PLATEAU;
    public static final Biome SAVANNA_ROCK;
    public static final Biome BADLANDS;
    public static final Biome MESA;
    public static final Biome WOODED_BADLANDS_PLATEAU;
    public static final Biome MESA_PLATEAU_F;
    public static final Biome MESA_ROCK;
    public static final Biome BADLANDS_PLATEAU;
    public static final Biome MESA_PLATEAU;
    public static final Biome MESA_CLEAR_ROCK;
    public static final Biome SMALL_END_ISLANDS;
    public static final Biome END_MIDLANDS;
    public static final Biome END_HIGHLANDS;
    public static final Biome END_BARRENS;
    public static final Biome WARM_OCEAN;
    public static final Biome LUKEWARM_OCEAN;
    public static final Biome COLD_OCEAN;
    public static final Biome DEEP_WARM_OCEAN;
    public static final Biome DEEP_LUKEWARM_OCEAN;
    public static final Biome DEEP_COLD_OCEAN;
    public static final Biome DEEP_FROZEN_OCEAN;
    public static final Biome THE_VOID;
    public static final Biome VOID;
    public static final Biome SUNFLOWER_PLAINS;
    public static final Biome MUTATED_PLAINS;
    public static final Biome DESERT_LAKES;
    public static final Biome DESERT_M;
    public static final Biome MUTATED_DESERT;
    public static final Biome GRAVELLY_MOUNTAINS;
    public static final Biome EXTREME_HILLS_M;
    public static final Biome MUTATED_EXTREME_HILLS;
    public static final Biome FLOWER_FOREST;
    public static final Biome MUTATED_FOREST;
    public static final Biome TAIGA_MOUNTAINS;
    public static final Biome TAIGA_M;
    public static final Biome MUTATED_TAIGA;
    public static final Biome SWAMP_HILLS;
    public static final Biome SWAMPLAND_M;
    public static final Biome MUTATED_SWAMPLAND;
    public static final Biome ICE_SPIKES;
    public static final Biome ICE_PLAINS_SPIKES;
    public static final Biome MUTATED_ICE_FLATS;
    public static final Biome MODIFIED_JUNGLE;
    public static final Biome JUNGLE_M;
    public static final Biome MUTATED_JUNGLE;
    public static final Biome MODIFIED_JUNGLE_EDGE;
    public static final Biome JUNGLE_EDGE_M;
    public static final Biome MUTATED_JUNGLE_EDGE;
    public static final Biome TALL_BIRCH_FOREST;
    public static final Biome BIRCH_FOREST_M;
    public static final Biome MUTATED_BIRCH_FOREST;
    public static final Biome TALL_BIRCH_HILLS;
    public static final Biome BIRCH_FOREST_HILLS_M;
    public static final Biome MUTATED_BIRCH_FOREST_HILLS;
    public static final Biome DARK_FOREST_HILLS;
    public static final Biome ROOFED_FOREST_M;
    public static final Biome MUTATED_ROOFED_FOREST;
    public static final Biome SNOWY_TAIGA_MOUNTAINS;
    public static final Biome COLD_TAIGA_M;
    public static final Biome MUTATED_TAIGA_COLD;
    public static final Biome GIANT_SPRUCE_TAIGA;
    public static final Biome MEGA_SPRUCE_TAIGA;
    public static final Biome MUTATED_REDWOOD_TAIGA;
    public static final Biome GIANT_SPRUCE_TAIGA_HILLS;
    public static final Biome MODIFIED_GRAVELLY_MOUNTAINS;
    public static final Biome SHATTERED_SAVANNA;
    public static final Biome SHATTERED_SAVANNA_PLATEAU;
    public static final Biome ERODED_BADLANDS;
    public static final Biome MODIFIED_WOODED_BADLANDS_PLATEAU;
    public static final Biome MODIFIED_BADLANDS_PLATEAU;
    public static final Biome BAMBOO_JUNGLE;
    public static final Biome BAMBOO_JUNGLE_HILLS;
    public static final Biome SOUL_SAND_VALLEY;
    public static final Biome CRIMSON_FOREST;
    public static final Biome WARPED_FOREST;
    public static final Biome BASALT_DELTAS;

    public static Biome register(Biome biome) {
        REGISTRY.put(biome.getId(), biome);
        return biome;
    }

    static {
        EXTREME_HILLS = MOUNTAINS = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.OVERWORLD, 3, "mountains", Biome.Category.EXTREME_HILLS, Biome.Precipitation.RAIN, 0.2f, 0.5f, 1.0f, null, ConfiguredSurfaceBuilders.MOUNTAIN));
        FOREST = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.OVERWORLD, 4, "forest", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.7f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.GRASS));
        TAIGA = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.OVERWORLD, 5, "taiga", Biome.Category.TAIGA, Biome.Precipitation.RAIN, 0.25f, 0.2f, 0.2f, null, ConfiguredSurfaceBuilders.GRASS));
        SWAMPLAND = SWAMP = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.OVERWORLD, 6, "swamp", Biome.Category.SWAMP, Biome.Precipitation.RAIN, 0.8f, 0.1f, -0.2f, null, ConfiguredSurfaceBuilders.SWAMP));
        RIVER = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.OVERWORLD, 7, "river", Biome.Category.RIVER, Biome.Precipitation.RAIN, 0.5f, 0.0f, -0.5f, null, ConfiguredSurfaceBuilders.GRASS));
        HELL = NETHER_WASTES = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.NETHER, 8, "nether_wastes", Biome.Category.NETHER, Biome.Precipitation.NONE, 2.0f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.NETHER));
        SKY = THE_END = Biomes.register(new Biome(MCVersion.vb1_8_1, Dimension.END, 9, "the_end", Biome.Category.THE_END, Biome.Precipitation.NONE, 0.5f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.END));
        FROZEN_OCEAN = Biomes.register(new Biome(MCVersion.v1_0, Dimension.OVERWORLD, 10, "frozen_ocean", Biome.Category.OCEAN, Biome.Precipitation.SNOW, 0.0f, 0.1f, -1.0f, null, ConfiguredSurfaceBuilders.FROZEN_OCEAN));
        FROZEN_RIVER = Biomes.register(new Biome(MCVersion.v1_0, Dimension.OVERWORLD, 11, "frozen_river", Biome.Category.RIVER, Biome.Precipitation.SNOW, 0.0f, 0.0f, -0.5f, null, ConfiguredSurfaceBuilders.GRASS));
        ICE_PLAINS = SNOWY_TUNDRA = Biomes.register(new Biome(MCVersion.v1_0, Dimension.OVERWORLD, 12, "snowy_tundra", Biome.Category.ICY, Biome.Precipitation.SNOW, 0.0f, 0.05f, 0.125f, null, ConfiguredSurfaceBuilders.GRASS));
        ICE_FLATS = SNOWY_TUNDRA;
        ICE_MOUNTAINS = SNOWY_MOUNTAINS = Biomes.register(new Biome(MCVersion.v1_0, Dimension.OVERWORLD, 13, "snowy_mountains", Biome.Category.ICY, Biome.Precipitation.SNOW, 0.0f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.GRASS));
        MUSHROOM_ISLAND = MUSHROOM_FIELDS = Biomes.register(new Biome(MCVersion.v1_0, Dimension.OVERWORLD, 14, "mushroom_fields", Biome.Category.MUSHROOM, Biome.Precipitation.RAIN, 0.9f, 0.3f, 0.2f, null, ConfiguredSurfaceBuilders.MYCELIUM));
        MUSHROOM_ISLAND_SHORE = MUSHROOM_FIELD_SHORE = Biomes.register(new Biome(MCVersion.v1_0, Dimension.OVERWORLD, 15, "mushroom_field_shore", Biome.Category.MUSHROOM, Biome.Precipitation.RAIN, 0.9f, 0.025f, 0.0f, null, ConfiguredSurfaceBuilders.MYCELIUM));
        BEACHEs = BEACH = Biomes.register(new Biome(MCVersion.v1_1, Dimension.OVERWORLD, 16, "beach", Biome.Category.BEACH, Biome.Precipitation.RAIN, 0.8f, 0.025f, 0.0f, null, ConfiguredSurfaceBuilders.DESERT));
        DESERT_HILLS = Biomes.register(new Biome(MCVersion.v1_1, Dimension.OVERWORLD, 17, "desert_hills", Biome.Category.DESERT, Biome.Precipitation.NONE, 2.0f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.DESERT));
        FOREST_HILLS = WOODED_HILLS = Biomes.register(new Biome(MCVersion.v1_1, Dimension.OVERWORLD, 18, "wooded_hills", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.7f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.GRASS));
        TAIGA_HILLS = Biomes.register(new Biome(MCVersion.v1_1, Dimension.OVERWORLD, 19, "taiga_hills", Biome.Category.TAIGA, Biome.Precipitation.RAIN, 0.25f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.GRASS));
        EXTREME_HILLS_EDGE = MOUNTAIN_EDGE = Biomes.register(new Biome(MCVersion.v1_1, Dimension.OVERWORLD, 20, "mountain_edge", Biome.Category.EXTREME_HILLS, Biome.Precipitation.RAIN, 0.2f, 0.3f, 0.8f, null, ConfiguredSurfaceBuilders.GRASS));
        SMALLER_EXTREME_HILLS = MOUNTAIN_EDGE;
        JUNGLE = Biomes.register(new Biome(MCVersion.v1_2_1, Dimension.OVERWORLD, 21, "jungle", Biome.Category.JUNGLE, Biome.Precipitation.RAIN, 0.95f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.GRASS));
        JUNGLE_HILLS = Biomes.register(new Biome(MCVersion.v1_2_1, Dimension.OVERWORLD, 22, "jungle_hills", Biome.Category.JUNGLE, Biome.Precipitation.RAIN, 0.95f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.GRASS));
        JUNGLE_EDGE = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 23, "jungle_edge", Biome.Category.JUNGLE, Biome.Precipitation.RAIN, 0.95f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.GRASS));
        DEEP_OCEAN = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 24, "deep_ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.8f, null, ConfiguredSurfaceBuilders.GRASS));
        STONE_BEACH = STONE_SHORE = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 25, "stone_shore", Biome.Category.NONE, Biome.Precipitation.RAIN, 0.2f, 0.8f, 0.1f, null, ConfiguredSurfaceBuilders.STONE));
        COLD_BEACH = SNOWY_BEACH = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 26, "snowy_beach", Biome.Category.BEACH, Biome.Precipitation.SNOW, 0.05f, 0.025f, 0.0f, null, ConfiguredSurfaceBuilders.DESERT));
        BIRCH_FOREST = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 27, "birch_forest", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.6f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.GRASS));
        BIRCH_FOREST_HILLS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 28, "birch_forest_hills", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.6f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.GRASS));
        ROOFED_FOREST = DARK_FOREST = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 29, "dark_forest", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.7f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.GRASS));
        COLD_TAIGA = SNOWY_TAIGA = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 30, "snowy_taiga", Biome.Category.TAIGA, Biome.Precipitation.SNOW, -0.5f, 0.2f, 0.2f, null, ConfiguredSurfaceBuilders.GRASS));
        COLD_TAIGA_HILLs = SNOWY_TAIGA_HILLS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 31, "snowy_taiga_hills", Biome.Category.TAIGA, Biome.Precipitation.SNOW, -0.5f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.GRASS));
        MEGA_TAIGA = GIANT_TREE_TAIGA = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 32, "giant_tree_taiga", Biome.Category.TAIGA, Biome.Precipitation.RAIN, 0.3f, 0.2f, 0.2f, null, ConfiguredSurfaceBuilders.GIANT_TREE_TAIGA));
        REDWOOD_TAIGA = GIANT_TREE_TAIGA;
        MEGA_TAIGA_HILLs = GIANT_TREE_TAIGA_HILLS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 33, "giant_tree_taiga_hills", Biome.Category.TAIGA, Biome.Precipitation.RAIN, 0.3f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.GIANT_TREE_TAIGA));
        REDWOOD_TAIGA_HILLs = GIANT_TREE_TAIGA_HILLS;
        EXTREME_HILLS_PLUS = WOODED_MOUNTAINS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 34, "wooded_mountains", Biome.Category.EXTREME_HILLS, Biome.Precipitation.RAIN, 0.2f, 0.5f, 1.0f, null, ConfiguredSurfaceBuilders.GRASS));
        EXTREME_HILLS_WITH_TREES = WOODED_MOUNTAINS;
        SAVANNA = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 35, "savanna", Biome.Category.SAVANNA, Biome.Precipitation.NONE, 1.2f, 0.05f, 0.125f, null, ConfiguredSurfaceBuilders.GRASS));
        SAVANNA_ROCK = SAVANNA_PLATEAU = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 36, "savanna_plateau", Biome.Category.SAVANNA, Biome.Precipitation.NONE, 1.0f, 0.025f, 1.5f, null, ConfiguredSurfaceBuilders.GRASS));
        MESA = BADLANDS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 37, "badlands", Biome.Category.MESA, Biome.Precipitation.NONE, 2.0f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.BADLANDS));
        MESA_PLATEAU_F = WOODED_BADLANDS_PLATEAU = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 38, "wooded_badlands_plateau", Biome.Category.MESA, Biome.Precipitation.NONE, 2.0f, 0.025f, 1.5f, null, ConfiguredSurfaceBuilders.WOODED_BADLANDS));
        MESA_ROCK = WOODED_BADLANDS_PLATEAU;
        MESA_PLATEAU = BADLANDS_PLATEAU = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 39, "badlands_plateau", Biome.Category.MESA, Biome.Precipitation.NONE, 2.0f, 0.025f, 1.5f, null, ConfiguredSurfaceBuilders.BADLANDS));
        MESA_CLEAR_ROCK = BADLANDS_PLATEAU;
        SMALL_END_ISLANDS = Biomes.register(new Biome(MCVersion.v1_13, Dimension.END, 40, "small_end_islands", Biome.Category.THE_END, Biome.Precipitation.NONE, 0.5f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.END));
        END_MIDLANDS = Biomes.register(new Biome(MCVersion.v1_13, Dimension.END, 41, "end_midlands", Biome.Category.THE_END, Biome.Precipitation.NONE, 0.5f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.END));
        END_HIGHLANDS = Biomes.register(new Biome(MCVersion.v1_13, Dimension.END, 42, "end_highlands", Biome.Category.THE_END, Biome.Precipitation.NONE, 0.5f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.END));
        END_BARRENS = Biomes.register(new Biome(MCVersion.v1_13, Dimension.END, 43, "end_barrens", Biome.Category.THE_END, Biome.Precipitation.NONE, 0.5f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.END));
        WARM_OCEAN = Biomes.register(new Biome(MCVersion.v1_13, Dimension.OVERWORLD, 44, "warm_ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.0f, null, ConfiguredSurfaceBuilders.FULL_SAND));
        LUKEWARM_OCEAN = Biomes.register(new Biome(MCVersion.v1_13, Dimension.OVERWORLD, 45, "lukewarm_ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.0f, null, ConfiguredSurfaceBuilders.OCEAN_SAND));
        COLD_OCEAN = Biomes.register(new Biome(MCVersion.v1_13, Dimension.OVERWORLD, 46, "cold_ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.0f, null, ConfiguredSurfaceBuilders.GRASS));
        DEEP_WARM_OCEAN = Biomes.register(new Biome(MCVersion.v1_13, Dimension.OVERWORLD, 47, "deep_warm_ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.8f, null, ConfiguredSurfaceBuilders.FULL_SAND));
        DEEP_LUKEWARM_OCEAN = Biomes.register(new Biome(MCVersion.v1_13, Dimension.OVERWORLD, 48, "deep_lukewarm_ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.8f, null, ConfiguredSurfaceBuilders.OCEAN_SAND));
        DEEP_COLD_OCEAN = Biomes.register(new Biome(MCVersion.v1_13, Dimension.OVERWORLD, 49, "deep_cold_ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.8f, null, ConfiguredSurfaceBuilders.GRASS));
        DEEP_FROZEN_OCEAN = Biomes.register(new Biome(MCVersion.v1_13, Dimension.OVERWORLD, 50, "deep_frozen_ocean", Biome.Category.OCEAN, Biome.Precipitation.RAIN, 0.5f, 0.1f, -1.8f, null, ConfiguredSurfaceBuilders.FROZEN_OCEAN));
        VOID = THE_VOID = Biomes.register(new Biome(MCVersion.v1_9, null, 127, "the_void", Biome.Category.NONE, Biome.Precipitation.NONE, 0.5f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.NOPE));
        MUTATED_PLAINS = SUNFLOWER_PLAINS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 129, "sunflower_plains", Biome.Category.PLAINS, Biome.Precipitation.RAIN, 0.8f, 0.05f, 0.125f, PLAINS, ConfiguredSurfaceBuilders.GRASS));
        DESERT_M = DESERT_LAKES = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 130, "desert_lakes", Biome.Category.DESERT, Biome.Precipitation.NONE, 2.0f, 0.25f, 0.225f, DESERT, ConfiguredSurfaceBuilders.DESERT));
        MUTATED_DESERT = DESERT_LAKES;
        EXTREME_HILLS_M = GRAVELLY_MOUNTAINS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 131, "gravelly_mountains", Biome.Category.EXTREME_HILLS, Biome.Precipitation.RAIN, 0.2f, 0.5f, 1.0f, MOUNTAINS, ConfiguredSurfaceBuilders.GRAVELLY_MOUNTAIN));
        MUTATED_EXTREME_HILLS = GRAVELLY_MOUNTAINS;
        MUTATED_FOREST = FLOWER_FOREST = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 132, "flower_forest", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.7f, 0.4f, 0.1f, FOREST, ConfiguredSurfaceBuilders.GRASS));
        TAIGA_M = TAIGA_MOUNTAINS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 133, "taiga_mountains", Biome.Category.TAIGA, Biome.Precipitation.RAIN, 0.25f, 0.4f, 0.3f, TAIGA, ConfiguredSurfaceBuilders.GRASS));
        MUTATED_TAIGA = TAIGA_MOUNTAINS;
        SWAMPLAND_M = SWAMP_HILLS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 134, "swamp_hills", Biome.Category.SWAMP, Biome.Precipitation.RAIN, 0.8f, 0.3f, -0.1f, SWAMP, ConfiguredSurfaceBuilders.SWAMP));
        MUTATED_SWAMPLAND = SWAMP_HILLS;
        ICE_PLAINS_SPIKES = ICE_SPIKES = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 140, "ice_spikes", Biome.Category.ICY, Biome.Precipitation.SNOW, 0.0f, 0.45f, 0.425f, SNOWY_TUNDRA, ConfiguredSurfaceBuilders.ICE_SPIKES));
        MUTATED_ICE_FLATS = ICE_SPIKES;
        JUNGLE_M = MODIFIED_JUNGLE = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 149, "modified_jungle", Biome.Category.JUNGLE, Biome.Precipitation.RAIN, 0.95f, 0.4f, 0.2f, JUNGLE, ConfiguredSurfaceBuilders.GRASS));
        MUTATED_JUNGLE = MODIFIED_JUNGLE;
        JUNGLE_EDGE_M = MODIFIED_JUNGLE_EDGE = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 151, "modified_jungle_edge", Biome.Category.JUNGLE, Biome.Precipitation.RAIN, 0.95f, 0.4f, 0.2f, JUNGLE_EDGE, ConfiguredSurfaceBuilders.GRASS));
        MUTATED_JUNGLE_EDGE = MODIFIED_JUNGLE_EDGE;
        BIRCH_FOREST_M = TALL_BIRCH_FOREST = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 155, "tall_birch_forest", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.6f, 0.4f, 0.2f, BIRCH_FOREST, ConfiguredSurfaceBuilders.GRASS));
        MUTATED_BIRCH_FOREST = TALL_BIRCH_FOREST;
        BIRCH_FOREST_HILLS_M = TALL_BIRCH_HILLS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 156, "tall_birch_hills", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.6f, 0.5f, 0.55f, BIRCH_FOREST_HILLS, ConfiguredSurfaceBuilders.GRASS));
        MUTATED_BIRCH_FOREST_HILLS = TALL_BIRCH_HILLS;
        ROOFED_FOREST_M = DARK_FOREST_HILLS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 157, "dark_forest_hills", Biome.Category.FOREST, Biome.Precipitation.RAIN, 0.7f, 0.4f, 0.2f, DARK_FOREST, ConfiguredSurfaceBuilders.GRASS));
        MUTATED_ROOFED_FOREST = DARK_FOREST_HILLS;
        COLD_TAIGA_M = SNOWY_TAIGA_MOUNTAINS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 158, "snowy_taiga_mountains", Biome.Category.TAIGA, Biome.Precipitation.SNOW, -0.5f, 0.4f, 0.3f, SNOWY_TAIGA, ConfiguredSurfaceBuilders.GRASS));
        MUTATED_TAIGA_COLD = SNOWY_TAIGA_MOUNTAINS;
        MEGA_SPRUCE_TAIGA = GIANT_SPRUCE_TAIGA = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 160, "giant_spruce_taiga", Biome.Category.TAIGA, Biome.Precipitation.RAIN, 0.25f, 0.2f, 0.2f, GIANT_TREE_TAIGA, ConfiguredSurfaceBuilders.GIANT_TREE_TAIGA));
        MUTATED_REDWOOD_TAIGA = GIANT_SPRUCE_TAIGA;
        GIANT_SPRUCE_TAIGA_HILLS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 161, "giant_spruce_taiga_hills", Biome.Category.TAIGA, Biome.Precipitation.RAIN, 0.25f, 0.2f, 0.2f, GIANT_TREE_TAIGA_HILLS, ConfiguredSurfaceBuilders.GIANT_TREE_TAIGA));
        MODIFIED_GRAVELLY_MOUNTAINS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 162, "modified_gravelly_mountains", Biome.Category.EXTREME_HILLS, Biome.Precipitation.RAIN, 0.2f, 0.5f, 1.0f, WOODED_MOUNTAINS, ConfiguredSurfaceBuilders.GRAVELLY_MOUNTAIN));
        SHATTERED_SAVANNA = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 163, "shattered_savanna", Biome.Category.SAVANNA, Biome.Precipitation.NONE, 1.1f, 1.225f, 0.3625f, SAVANNA, ConfiguredSurfaceBuilders.SHATTERED_SAVANNA));
        SHATTERED_SAVANNA_PLATEAU = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 164, "shattered_savanna_plateau", Biome.Category.SAVANNA, Biome.Precipitation.NONE, 1.0f, 1.212f, 1.05f, SAVANNA_PLATEAU, ConfiguredSurfaceBuilders.SHATTERED_SAVANNA));
        ERODED_BADLANDS = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 165, "eroded_badlands", Biome.Category.MESA, Biome.Precipitation.NONE, 2.0f, 0.2f, 0.1f, BADLANDS, ConfiguredSurfaceBuilders.ERODED_BADLANDS));
        MODIFIED_WOODED_BADLANDS_PLATEAU = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 166, "modified_wooded_badlands_plateau", Biome.Category.MESA, Biome.Precipitation.NONE, 2.0f, 0.3f, 0.45f, WOODED_BADLANDS_PLATEAU, ConfiguredSurfaceBuilders.WOODED_BADLANDS));
        MODIFIED_BADLANDS_PLATEAU = Biomes.register(new Biome(MCVersion.v1_7_2, Dimension.OVERWORLD, 167, "modified_badlands_plateau", Biome.Category.MESA, Biome.Precipitation.NONE, 2.0f, 0.3f, 0.45f, BADLANDS_PLATEAU, ConfiguredSurfaceBuilders.BADLANDS));
        BAMBOO_JUNGLE = Biomes.register(new Biome(MCVersion.v1_14, Dimension.OVERWORLD, 168, "bamboo_jungle", Biome.Category.JUNGLE, Biome.Precipitation.RAIN, 0.95f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.GRASS));
        BAMBOO_JUNGLE_HILLS = Biomes.register(new Biome(MCVersion.v1_14, Dimension.OVERWORLD, 169, "bamboo_jungle_hills", Biome.Category.JUNGLE, Biome.Precipitation.RAIN, 0.95f, 0.3f, 0.45f, null, ConfiguredSurfaceBuilders.GRASS));
        SOUL_SAND_VALLEY = Biomes.register(new Biome(MCVersion.v1_16, Dimension.NETHER, 170, "soul_sand_valley", Biome.Category.NETHER, Biome.Precipitation.NONE, 2.0f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.SOUL_SAND_VALLEY));
        CRIMSON_FOREST = Biomes.register(new Biome(MCVersion.v1_16, Dimension.NETHER, 171, "crimson_forest", Biome.Category.NETHER, Biome.Precipitation.NONE, 2.0f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.CRIMSON_FOREST));
        WARPED_FOREST = Biomes.register(new Biome(MCVersion.v1_16, Dimension.NETHER, 172, "warped_forest", Biome.Category.NETHER, Biome.Precipitation.NONE, 2.0f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.WARPED_FOREST));
        BASALT_DELTAS = Biomes.register(new Biome(MCVersion.v1_16, Dimension.NETHER, 173, "basalt_deltas", Biome.Category.NETHER, Biome.Precipitation.NONE, 2.0f, 0.2f, 0.1f, null, ConfiguredSurfaceBuilders.BASALT_DELTAS));
    }
}

